# -*- coding: utf-8 -*-
"""Email_sender_using_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wsDQm4IiqbNAuMo6q2yyl2l6R9U_2n8A
"""

import smtplib

to = input("Enter the Email of sender (email id of who you want to send): \n")
content = input("Enter the content for sending: \n")

def sendEmail(to, content):
  server = smtplib.SMTP('smtp.gmail.com', 587)
  server.ehlo()
  server.starttls()
  server.login('your_gmail_id@gmail.com', 'Password_of_your_gamil')
  server.sendmail('your_gmail_id@gmail.com', to, content)
  server.close()

sendEmail(to, content)

